---
# Simple Ansible to load up the var files, and to run the task
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  vars_files:
    - "vars/{{environment_file}}"
    - "vars/envmapping.yaml"
  tasks:
    - include_tasks: "playbooks/{{tasks}}"
